//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GewProductivityAppService.DAL.MIS01.Temp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<usp_GetSendInfo_Result> usp_GetSendInfo(string sCode, string current_Department, Nullable<int> iType)
        {
            var sCodeParameter = sCode != null ?
                new ObjectParameter("sCode", sCode) :
                new ObjectParameter("sCode", typeof(string));
    
            var current_DepartmentParameter = current_Department != null ?
                new ObjectParameter("Current_Department", current_Department) :
                new ObjectParameter("Current_Department", typeof(string));
    
            var iTypeParameter = iType.HasValue ?
                new ObjectParameter("iType", iType) :
                new ObjectParameter("iType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSendInfo_Result>("usp_GetSendInfo", sCodeParameter, current_DepartmentParameter, iTypeParameter);
        }
    }
}
